server:
  port: 8074

spring:
  datasource:
    druid:
      filters: stat,wall
      maxActive: 10
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      url: jdbc:mysql://123.207.160.177:3308/fish_dev?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: yuyu1995
    name: test
    url: jdbc:mysql://---/fish_dev?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ---
    password: ---
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: true
    check-template-location: true
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:/webCrawer/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  configuration.map-underscore-to-camel-case : true
  configuration:
    cache-enabled: true
    aggressive-lazy-loading: true  #延迟加载：使用到相关字段的时候才进行关联表查询

    